package spider


// Auto Generated by https://mholt.github.io/json-to-go/


type PositionResp struct {
	RequestID     interface{} `json:"requestId"`
	Success       bool        `json:"success"`
	Msg           interface{} `json:"msg"`
	ResubmitToken interface{} `json:"resubmitToken"`
	Content `json:"content"`
	Code int `json:"code"`
}

type Content struct  {

	PageNo    int `json:"pageNo"`
	PageSize  int `json:"pageSize"`
	HrInfoMap struct {
		Num1286665 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     interface{} `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"1286665"`
		Num3269743 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     interface{} `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"3269743"`
		Num3850311 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     interface{} `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"3850311"`
		Num3997108 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     interface{} `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"3997108"`
		Num4078284 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     interface{} `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4078284"`
		Num4239814 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     string      `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4239814"`
		Num4394572 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     interface{} `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4394572"`
		Num4497506 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     string      `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4497506"`
		Num4500719 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     string      `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4500719"`
		Num4607995 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     string      `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4607995"`
		Num4628922 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     string      `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4628922"`
		Num4719523 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     string      `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4719523"`
		Num4731577 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     interface{} `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4731577"`
		Num4778288 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     string      `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4778288"`
		Num4789033 struct {
			UserID       int         `json:"userId"`
			Phone        interface{} `json:"phone"`
			PositionName string      `json:"positionName"`
			UserLevel    string      `json:"userLevel"`
			ReceiveEmail interface{} `json:"receiveEmail"`
			RealName     string      `json:"realName"`
			Portrait     string      `json:"portrait"`
			CanTalk      bool        `json:"canTalk"`
		} `json:"4789033"`
	} `json:"hrInfoMap"`
	PositionResult struct {
		TotalCount   int         `json:"totalCount"`
		HotLabels    interface{} `json:"hotLabels"`
		LocationInfo struct {
			City                 interface{} `json:"city"`
			District             interface{} `json:"district"`
			QueryByGisCode       bool        `json:"queryByGisCode"`
			BusinessZone         interface{} `json:"businessZone"`
			LocationCode         interface{} `json:"locationCode"`
			IsAllhotBusinessZone bool        `json:"isAllhotBusinessZone"`
		} `json:"locationInfo"`
		QueryAnalysisInfo struct {
			CompanyName   interface{} `json:"companyName"`
			PositionName  string      `json:"positionName"`
			JobNature     interface{} `json:"jobNature"`
			IndustryName  interface{} `json:"industryName"`
			UsefulCompany bool        `json:"usefulCompany"`
		} `json:"queryAnalysisInfo"`
		StrategyProperty struct {
			Name string `json:"name"`
			ID   int    `json:"id"`
		} `json:"strategyProperty"`
		HiTags     interface{} `json:"hiTags"`
		ResultSize int         `json:"resultSize"`
		Result     []Position `json:"result"`
	} `json:"positionResult"`

}

type Position struct {
	CompanyID             int           `json:"companyId"`
	FinanceStage          string        `json:"financeStage"`
	CompanyLogo           string        `json:"companyLogo"`
	IndustryField         string        `json:"industryField"`
	CompanyShortName      string        `json:"companyShortName"`
	City                  string        `json:"city"`
	Salary                string        `json:"salary"`
	PositionID            int           `json:"positionId"`
	PositionAdvantage     string        `json:"positionAdvantage"`
	District              string        `json:"district"`
	CreateTime            string        `json:"createTime"`
	PositionName          string        `json:"positionName"`
	WorkYear              string        `json:"workYear"`
	Education             string        `json:"education"`
	JobNature             string        `json:"jobNature"`
	Score                 int           `json:"score"`
	Approve               int           `json:"approve"`
	PositionLables        []interface{} `json:"positionLables"`
	IndustryLables        []interface{} `json:"industryLables"`
	PublisherID           int           `json:"publisherId"`
	CompanyLabelList      []string      `json:"companyLabelList"`
	CompanySize           string        `json:"companySize"`
	BusinessZones         []string      `json:"businessZones"`
	Longitude             string        `json:"longitude"`
	Latitude              string        `json:"latitude"`
	FormatCreateTime      string        `json:"formatCreateTime"`
	Hitags                interface{}   `json:"hitags"`
	ResumeProcessRate     int           `json:"resumeProcessRate"`
	ResumeProcessDay      int           `json:"resumeProcessDay"`
	ImState               string        `json:"imState"`
	LastLogin             int64         `json:"lastLogin"`
	Explain               interface{}   `json:"explain"`
	Plus                  interface{}   `json:"plus"`
	PcShow                int           `json:"pcShow"`
	AppShow               int           `json:"appShow"`
	Deliver               int           `json:"deliver"`
	GradeDescription      interface{}   `json:"gradeDescription"`
	PromotionScoreExplain interface{}   `json:"promotionScoreExplain"`
	FirstType             string        `json:"firstType"`
	SecondType            string        `json:"secondType"`
	IsSchoolJob           int           `json:"isSchoolJob"`
	Subwayline            string        `json:"subwayline"`
	Stationname           string        `json:"stationname"`
	Linestaion            string        `json:"linestaion"`
	CompanyFullName       string        `json:"companyFullName"`
	AdWord                int           `json:"adWord"`
}
